- hosts: all
    
  tasks:

  - name: Check system information
    ansible.builtin.shell: "lsb_release -a"
    register: results
  - name: output results
    ansible.builtin.debug:
      var: results
    
 
